name: Tests

on:
  push:
    branches:
     - master
  pull_request_target:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: DevExpress/testcafe-build-system/actions/prepare@main
      
      - uses: DevExpress/testcafe-build-system/actions/build@main
      
     
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: DevExpress/testcafe-build-system/actions/prepare@main
      
      - uses: DevExpress/testcafe-build-system/actions/test-npm@main
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        with:
          task: test
 
